export const SCHEMES = {
    kanagawa: {
        // https://github.com/rebelot/kanagawa.nvim
        name: "Kanagawa",
        mode: "dark",
        colors: {
            primary: "#7e9cd8",
            secondary: "#54546d",
            body: "#dcd7ba",
            bodyLight: "#dcd7ba",
            bodyDark: "#2a2a37",
            background: "#1f1f28",
            backgroundNav: "#2a2a37",
            muted: "#54546d",

            success: "#98bb6c",
            danger: "#ff5d62",
            warning: "#ffa066",
            info: "#7fb4ca",

            orange: "#ffa066",
            yellow: "#e6c384",
            green: "#98bb6c",
            aqua: "#7aa89f",
            blue: "#a3d4d5",
            purple: "#957fb8",
            pink: "#d27e99",
            gray: "#54546d",
        },
    },
    monokai_pro: {
        // Harder to find a palette, but here's where these were taken:
        // https://github.com/loctvl842/monokai-pro.nvim/blob/master/lua/monokai-pro/colorscheme/palette/pro.lua
        name: "Monokai Pro",
        mode: "dark",
        colors: {
            primary: "#ffd866",
            secondary: "#ff6188",
            body: "#fcfcfa",
            bodyLight: "#fcfcfa",
            bodyDark: "#3c393d",
            background: "#2d2a2e",
            backgroundNav: "#221f22",
            muted: "#696769",

            success: "#a9dc76",
            danger: "#ff6188",
            warning: "#fc9867",
            info: "#78dce8",

            orange: "#fc9867",
            yellow: "#ffd866",
            green: "#a9dc76",
            aqua: "#78fad4",
            blue: "#78dce8",
            purple: "#ab9df2",
            pink: "#ff6188",
            gray: "#727072",
        },
    },
    dracula: {
        // https://github.com/dracula/dracula-theme
        name: "Dracula",
        mode: "dark",
        colors: {
            primary: "#bd93f9",
            secondary: "#50fa7b",
            body: "#f8f8f2",
            bodyLight: "#f8f8f2",
            bodyDark: "#44475a",
            background: "#282a36",
            backgroundNav: "#44475a",
            muted: "#585b74",

            success: "#50fa7b",
            danger: "#ff5555",
            warning: "#ffb86c",
            info: "#8be9fd",

            orange: "#ffb86c",
            yellow: "#f1fa8c",
            green: "#50fa7b",
            aqua: "#8be9fd",
            blue: "#6272a4",
            purple: "#bd93f9",
            pink: "#ff79c6",
            gray: "#585b74",
        },
    },
    gruvbox_dark: {
        // https://github.com/morhetz/gruvbox
        name: "Gruvbox Dark",
        mode: "dark",
        colors: {
            primary: "#b8bb26",
            secondary: "#665c54",
            body: "#ebdbb2",
            bodyLight: "#ebdbb2",
            bodyDark: "#3c3836",
            background: "#282828",
            backgroundNav: "#3c3836",
            muted: "#727169",

            success: "#b8bb26",
            danger: "#fb4934",
            warning: "#fabd2e",
            info: "#83a598",

            orange: "#fe8019",
            yellow: "#fabd2f",
            green: "#b8bb26",
            aqua: "#8ec07c",
            blue: "#83a598",
            purple: "#b16286",
            pink: "#d3869b",
            gray: "#928374",
        },
    },
    gruvbox_light: {
        // https://github.com/morhetz/gruvbox
        name: "Gruvbox Light",
        mode: "light",
        colors: {
            primary: "#af3a03",
            secondary: "#7c6f64",
            body: "#3c3836",
            bodyLight: "#f9f5d7",
            bodyDark: "#3c3836",
            background: "#fbf1c7",
            backgroundNav: "#f9f5d7",
            muted: "#7c6f64",

            success: "#79740e",
            danger: "#9d0006",
            warning: "#b57614",
            info: "#076678",

            orange: "#d65d0e",
            yellow: "#b57614",
            green: "#79740e",
            aqua: "#427b58",
            blue: "#076678",
            purple: "#8f3f71",
            pink: "#b16286",
            gray: "#7c6f64",
        },
    },
    pastel: {
        // Custom scheme
        name: "Pastel",
        mode: "light",
        colors: {
            primary: "#79a9d1",
            secondary: "#A6A6A6",
            body: "#64666b",
            bodyLight: "#f0ebdb",
            bodyDark: "#64666b",
            background: "#e9e2cc",
            backgroundNav: "#f0ebdb",
            muted: "#a6a6a6",

            success: "#77dd77",
            danger: "#ff6961",
            warning: "#ffb347",
            info: "#79a9d1",

            orange: "#ffb347",
            yellow: "#fff68f",
            green: "#77dd77",
            aqua: "#76d7c4",
            blue: "#79a9d1",
            purple: "#c39bd3",
            pink: "#f7b7d2",
            gray: "#c0c0c0",
        },
    },
};
